# Makefile for TCP example

cli-tcp.out: cli-tcp.c
	gcc -g cli-tcp.c -o cli-tcp.out

serv-tcp.out: serv-tcp.c
	gcc -g serv-tcp.c -o serv-tcp.out

int-tcp.out: int-tcp.c
	gcc -g int-tcp.c -o int-tcp.out

